name: Laundrix
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  d_button: ^0.0.10
  d_info: ^0.2.0
  d_input: ^0.1.3
  d_method: ^0.2.0
  d_view: ^0.0.5
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^4.0.4
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.2.6
  grouped_list: ^5.1.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
